# Generated by Django 5.1.3 on 2024-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_abstractcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcheck',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
